### ISSUE TITLE
Tighter integration on apps within Nextcloud ecosystem

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#10]
- [x] iOS: https://github.com/nextcloud/ios/issues/2460
- [x] Android: https://github.com/nextcloud/android/issues/11744

## see below for updated tasks
We have many good apps that are maybe not that well known and where users can benefit from a tighter integration.
This is "only" a rough overview, which then needs to be split up in smaller tasks.

**Comment by tobiasKaminsky** [comment]
Android Files:
- beneath community with gap
 - Talk, Notes, "more Nextcloud apps"
 - opens app if installed, if not open link to PlayStore or Fdroid
 - "more" -> open playstore/fdroid with filter for "Nextcloud"

iOS:
- beneath "Settings" gap with above same behaviour

**Comment by tobiasKaminsky** [comment]
PWA or similar are not scope of this issue.
The idea is to promote existing apps and not try to provide each and every feature as an "app" to users.

For a discussion on PWAs please create a topic on server repo, as those needed to be provided via web.

**Comment by tobiasKaminsky** [comment]
@jancborchardt which apps shall we show in "more" apps?
All server side apps? Like on Desktop?

**Comment by tobiasKaminsky** [comment]
> @jancborchardt which apps shall we show in "more" apps?
> All server side apps? Like on Desktop?



> * "more" -> open playstore/fdroid with filter for "Nextcloud"

Totally forgotten :see_no_evil:

**Comment by mpivchev** [comment]
> with multi account: open another app with correct account

@jancborchardt Are we sure we should do this? There might be cases where the user does not want to switch between accounts, and wants to use the ones set in each app.

**Comment by jancborchardt** [comment]
@mpivchev I'd say yeah, it would be expected to land in the same account you came from, if that one is configured inside the receiving app. (If not just land in the regular one.)

But if the app does not support multiple accounts or account switching, that's a different task.

**Comment by mpivchev** [comment]
> @mpivchev I'd say yeah, it would be expected to land in the same account you came from, if that one is configured inside the receiving app. (If not just land in the regular one.)
> 
> But if the app does not support multiple accounts or account switching, that's a different task.

Yes, all apps don't support this out of the gate:

- Notes needs multi user support, separate issue will be made
- Talk needs a deeplink URL support for switching accounts, issue will be made
- Files also needs a deeplink URL support for switching accounts for when we switch to it, I will make this so it's ready.
