### ISSUE TITLE
[Feature parity] Android & Desktop: remove local e2e key

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#30]
On iOS it is possible to remove e2e locally, if for example someone wants to give this device to their family.

We should do the same on Android & Desktop.

**Comment by tobiasKaminsky** [comment]
Android: https://github.com/nextcloud/android/pull/11031
Desktop: https://github.com/nextcloud/desktop/pull/5167

**Comment by joshtrichards** [comment]
All merged and released. Closing.

Android: https://github.com/nextcloud/android/pull/11031
Desktop: https://github.com/nextcloud/desktop/pull/5167
