### ISSUE TITLE
Show tags in file/folder listing

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#39]
- [x] Android: https://github.com/nextcloud/android/pull/11515
- [x] Android library: https://github.com/nextcloud/android-library/pull/1106
- [x] Desktop: https://github.com/nextcloud/desktop/pull/5596
- [x] iOS:
- Server 
  - [x] API: https://github.com/nextcloud/server/pull/37609
  - [x] https://github.com/nextcloud/server/pull/38066
- [x] Activity app: https://github.com/nextcloud/activity/issues/1147

Server:
Webdav property is: "tags".
Output:
```
<nc:sharees/>
<nc:tags>
  <oc:tag>test 0</oc:tag>
</nc:tags>
```
 
Android/iOS @tobiasKaminsky @marinofaggiana:
- show first tag as first entry in subline
- if more "+x"
- ellipsize tags
- use rounded borders similar to mockup below
- show all tags in details

Desktop @claucambra : 
~~in activity list (ping @nickvergessen if API change in needed), in subline, same as Android/iOS~~
- share options/file detail: beneath size/date
- use rounded borders similar to mockup below

Mockup:
![image](https://user-images.githubusercontent.com/5836855/230104942-256735fa-39ce-4b68-9b2e-5268f097abcc.png)

**Comment by tobiasKaminsky** [comment]
@marino you can use our e2e.kaminsky.me test server with PROPFIND:

PROPFIND with <tags  xmlns="http://nextcloud.org/ns"/>
results in:

<nc:tags>
					<oc:tag>test 0</oc:tag>
					<oc:tag>test 1</oc:tag>
					<oc:tag>test 2</oc:tag>
					<oc:tag>test 3</oc:tag>
				</nc:tags>
(nc vs oc might change, as this is strange right now)

**Comment by tobiasKaminsky** [comment]
Right now it is only for showing tags.
Nothing more is needed :)

**Comment by tobiasKaminsky** [comment]
iOS:
![image](https://user-images.githubusercontent.com/5836855/231367770-d6c0d709-ad39-42db-bfd9-915586d4f93b.png)

Android:
![image](https://user-images.githubusercontent.com/5836855/231367959-aef11e9a-095c-4642-bd0f-1af90c039d58.png)

@jancborchardt I am unsure if two lines will fit…It will then look on iOS also cluttered, same as on Android…

**Comment by claucambra** [comment]
Opened https://github.com/nextcloud/desktop/pull/5596

**Comment by claucambra** [comment]
> iOS: ![image](https://user-images.githubusercontent.com/5836855/231367770-d6c0d709-ad39-42db-bfd9-915586d4f93b.png)
> 
> Android: ![image](https://user-images.githubusercontent.com/5836855/231367959-aef11e9a-095c-4642-bd0f-1af90c039d58.png)
> 
> @jancborchardt I am unsure if two lines will fit…It will then look on iOS also cluttered, same as on Android…

Note we will have the same issue on activities on desktop, particularly for those that are already showing changes to several files

**Comment by tobiasKaminsky** [comment]
> How about if there are tags on a file, we just replace the current subline info about file size and date with the tags?
> Everything is still visible in the details.

Nice idea. Shall we then still only have one tag? and then "+x" as second?
Or shall we have 2 tags and then "+x"? 
(I have no idea how many tags usually are used…)

**Comment by jancborchardt** [comment]
We can definitely show more than one tag, however much space there is of course.

@tobiasKaminsky for Android the border color of the tag can be a bit lighter, and the tags are a bit too low compared to the size/date text.

@marinofaggiana for iOS it looks nice in the file list, good job! Can you there also show more than just 1 tag? 2 at least we could show, of course depending on length of text. :)

**Comment by tobiasKaminsky** [comment]
@marinofaggiana @claucambra we now have official API:
PROPFIND with <system-tags xmlns="http://nextcloud.org/ns"/>
results in:
```
<nc:system-tags>
					<nc:system-tag oc:can-assign="true" oc:id="3" oc:user-assignable="true" oc:user-visible="true">important</nc:system-tag>
				</nc:system-tags>
```

For us, right now, only name is important.

You can test it/use it on: 
e2e.kaminsky.me 
user: tag
