### ISSUE TITLE
Update folder and files icons

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#46]
- [x] Android: https://github.com/nextcloud/android/issues/11999 https://github.com/nextcloud/android/issues/12687
- [x] iOS https://github.com/nextcloud/ios/issues/2856
- [x] Desktop https://github.com/nextcloud/desktop/issues/6564

Ref: https://github.com/nextcloud/server/pull/40209

**Comment by allexzander** [comment]
desktop part is done, not so much icons are actually used locally, so I've updated only those in resources, rest is fetched from the server (activities)

**Comment by marcoambrosini** [comment]
Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A)
Document: [description](https://fonts.google.com/icons?selected=Material%20Icons%3Adescription%3A) in `#49abea`
Spreadsheet: [file-table-box](https://pictogrammers.com/library/mdi/icon/file-table-box/) in `#9abd4e`
Presentation: [file-presentation-box](https://pictogrammers.com/library/mdi/icon/file-presentation-box/) in `#f0965f`
Diagram: [drawing-box](https://pictogrammers.com/library/mdi/icon/drawing-box/) in `#ebc94a`
PDF: [picture-as-pdf](https://fonts.google.com/icons?selected=Material+Icons+Round:picture_as_pdf:&icon.query=pdf)
Image: [image](https://fonts.google.com/icons?selected=Material+Icons+Round:image:&icon.query=image)
Video: [movie](https://fonts.google.com/icons?selected=Material+Icons:movie:&icon.query=video)

@tobiasKaminsky @jancborchardt @nimishavijay any other you can think of?

**Comment by marcoambrosini** [comment]
Folder icons here

[Folder icons.zip](https://github.com/nextcloud/files-clients/files/14602901/Folder.icons.zip)

**Comment by marcoambrosini** [comment]
Reopening since the files icon were not updated yet

**Comment by AndyScherzinger** [comment]
Android mime type icon update PR at https://github.com/nextcloud/android/issues/12687

**Comment by AndyScherzinger** [comment]
I made the text file icon grey instead of black btw. Fine to change that if desired @marcoambrosini @nimishavijay

**Comment by AndyScherzinger** [comment]
Android Talk PR at https://github.com/nextcloud/talk-android/pull/3719

**Comment by Ivansss** [comment]
These icons are not being used in the web at the moment, are they going to be added in the Files web interface at some point as well?
* PDF: [picture-as-pdf](https://fonts.google.com/icons?selected=Material+Icons+Round:picture_as_pdf:&icon.query=pdf)
* Image: [image](https://fonts.google.com/icons?selected=Material+Icons+Round:image:&icon.query=image)
* Video: [movie](https://fonts.google.com/icons?selected=Material+Icons:movie:&icon.query=video)

@nextcloud/designers

**Comment by marcoambrosini** [comment]
Yes, that's the plan @Ivansss

**Comment by AndyScherzinger** [comment]
@marcoambrosini are you taking care of that or can you tell @sorbaugh to? Thanks in advance

Cc @Pytal maybe since he took care of other icons for the 'new' menu entries.

**Comment by Ivansss** [comment]
What colors should we use for these icons?
* Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A)
* PDF: [picture-as-pdf](https://fonts.google.com/icons?selected=Material+Icons+Round:picture_as_pdf:&icon.query=pdf)
* Image: [image](https://fonts.google.com/icons?selected=Material+Icons+Round:image:&icon.query=image)
* Video: [movie](https://fonts.google.com/icons?selected=Material+Icons:movie:&icon.query=video)

**Comment by Ivansss** [comment]
Also, just to clarify, in which situations will be used the document icon?
* Document: [description](https://fonts.google.com/icons?selected=Material%20Icons%3Adescription%3A) in `#49abea`

Are we going to have a new default file icon like this one?
https://github.com/nextcloud/server/blob/master/core/img/filetypes/file.svg

What about `audio`, `vcard`, and `zip` files icons?

@nextcloud/designers

**Comment by marcoambrosini** [comment]
@Ivansss document refers to a Nextcloud office document, I believe 

Do we need those icons too @jancborchardt ?

**Comment by jancborchardt** [comment]
@marcoambrosini if the current filetype icons are still non-material it could be nice to update them too? :)

**Comment by Pytal** [comment]
> These icons are not being used in the web at the moment, are they going to be added in the Files web interface at some point as well?
> 
> Cc @Pytal maybe since he took care of other icons for the 'new' menu entries.

Done in https://github.com/nextcloud/server/pull/44513
