### ISSUE TITLE
Deprecation of the old Metadata API

### ISSUE THREAD

**Issue by artonge** [nextcloud/files-clients#48]
The metadata API as been updated for NC 28, which means for clients that the DAV props `<nc:file-metadata-size>` and `<nc:file-metadata-gps>` are now called `<nc:metadata-photos-size>` and `<nc:metadata-photos-gps>`.

I think that at least the Android client is using the size prop for the media gallery.
They also do not need to be JSON parsed as the values come formatted in XML.

**Comment by tobiasKaminsky** [comment]
@marinofaggiana 
@alperozturk96
