### ISSUE TITLE
🔑 Client cert based auth

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#49]
- [x] Android https://github.com/nextcloud/android/issues/603
- [x] iOS https://github.com/nextcloud/ios/issues/847
- [ ] server: https://github.com/nextcloud/docker-ci/pull/616

**Comment by WinkelB** [comment]
> * [x]  Android [🔑 Support for client certificates android#603](https://github.com/nextcloud/android/issues/603)
> * [ ]  iOS [🔑 Use SSL Client Certificate to improve security ios#847](https://github.com/nextcloud/ios/issues/847)
> * [ ]  server: [🔑 Add client cert auth docker-ci#616](https://github.com/nextcloud/docker-ci/pull/616)

Im looking forward for this enhancement.
In the Overview are you missing the Desktop Application?
https://github.com/nextcloud/desktop

I've already created an Issue a while back.
https://github.com/nextcloud/desktop/issues/6493
