### ISSUE TITLE
🪟📁📄Windows compatible file names

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#58]
Server: https://github.com/nextcloud/server/issues/44963

Bugs
- [ ] https://github.com/nextcloud/deck/issues/6185
- [x] https://github.com/nextcloud/spreed/issues/12914
- [ ] https://github.com/nextcloud/photos/issues/2576
- [x] https://github.com/nextcloud/calendar/issues/6245
- [ ] https://github.com/nextcloud/notes/issues/1340
- [x] https://github.com/nextcloud/text/issues/6269
- [ ] Nextcloud Assistant: transcribe audio: unspecific error message when uploading a non-allowed file (I do not know which repo it is @DaphneMuller)

**Comment by tobiasKaminsky** [comment]
most important is https://github.com/nextcloud/server/issues/44963#issuecomment-2186666275

with Accept-Language: en,fr,de

we can later localize it, so that response returns correct language.

**Comment by tobiasKaminsky** [comment]
- test locally if name matches (obey 4 capabilities)
- send then to server
- show localized reply

"Endpoints"
- Webdav: copy, move, create
- apps can share to Nextcloud: how to check, report error?

**Comment by alperozturk96** [comment]
We need to cover the following use-cases for this feature

1. [Create a New Document] Tap the plus button on the home screen, select "New Document," and enter a file name for the new document.
2. [Rename a File] Tap the three dots icon at the end of any file in the list, and select "Rename."
3. [Rename a File From File Details] Go to "File Details". From the top right, tap the three dots icon, select "Rename," and test it.
4. [Create a New Folder] Tap the plus button on the home screen, select "New Folder," and enter a name for the new folder.
5. [Move or Copy file to Any Folder] Tap the three dots icon at the end of any file in the list, and select "Move" or "Copy." Attempt to move or copy to both an invalid and a valid folder path.
6. [Share a File From Other Any App] From any other app, try to share a file with the Nextcloud Files app. If the shared file contains invalid characters or reserved name, user must receive feedback, and the operation should not be allowed.
7. [Upload Contents From Other Apps] Tap the plus button on the home screen, select "Upload Contents from Other Apps." If the contents include a path, the user must receive feedback, and the operation should not be allowed.
8. [Create a New File From Other File Manager Apps] User can create forbidden file names from native files app such as Google Files.
9. [Create a New Template] User may have a template for creating office files such as new presentation and new text document etc

**Comment by claucambra** [comment]
Desktop client implementation: https://github.com/nextcloud/desktop/pull/6965
