### ISSUE TITLE
Offline CRUD: first create folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#59]
- detect device being offline
  - with ping interval of 5s to /200 endpoint
  - when operation fails
- store operations (e.g. delete folder, create folder)
- show them file list as "pending to be created"
- detect being online again
- executing pending operation

**Comment by alperozturk96** [comment]
```

data class Operation(
    val id: Long,
    val parentId: Long?, --> Is this operation not in the first place in the queue 
    val parentOCFileId: Long?, --> Where the operation will be executed. e.g. creating folder inside another folder, renaming file inside another folder or deleting file inside root

   --- OPTIONAL_FOR_ONLY_CREATE_FOLDER_OPERATIONS --
    val type: Enum, --> Create, Remove, Rename
    val path: String, --> Path of the file
     val createdAt: Long, --> When the operation is created. Can be useful for debugging purpose and cleaning table
    // val modifiedAt: Long?, --> When the operation is modified. User can modify the operation as well, in future maybe.
    // val status: String --> Status of the operation. Is it completed or, pending? If user cancel it remove from DB.
)
```

Maybe for starting from creating folder we don't need to have all these colums in table. Only id, parentId, parentOCFileId would be enough. Then we can migrate for rest operations.

**Comment by alperozturk96** [comment]
## Scenarios

#### Create Folder

1. **Conflict Resolution for Existing Folders:** When the user attempts to create a folder that already exists on the server while offline, a conflict resolution dialog should appear to handle the duplication.

2. **Queue Cleanup:** Any operations that are either completed or canceled should be automatically removed from the queue.

3. **Multiple Users Modifying the Same File:** If multiple offline users modify the same file or folder, the client must handle these conflicts when the users reconnect.

4. **Interrupted Execution Order:** If the user queues multiple operations, goes online during execution, then goes offline and online again, the system must maintain the correct execution order, even if some operations fail.

5. **Multi-Device Conflict Resolution:** If the user has multiple devices offline and makes changes to the same folder from different devices, conflicts should be properly resolved when all devices reconnect.

6. **Creating Encrypted Folders Offline:** The user should be able to create encrypted folders while offline, with the operation being queued for when they reconnect.

7. **Switching Accounts While Offline:** If the user switches accounts while offline, the operation queue must execute under the corresponding user ID when they reconnect.


#### For Other Operations (No Need To Implement Beforehand)

8. **Queue Management with Delete Operations:** If the user queues multiple operations and then attempts to delete a folder (or its parent) as the last operation, all preceding operations might become redundant. Additionally, the server could execute a delete operation while other queued operations are still pending, leading to potential conflicts.

9. **Offline File Sharing:** The user should be able to share any file or folder while offline, with the operation being queued for when they reconnect.

10. **Handling Rename Operations in Queue:** When the user queues multiple operations, if a rename operation is performed in the middle, all subsequent operations must take the rename into account. Similarly, if a delete operation occurs, the queue must adjust accordingly.

11. **Queue Operations on Deleted Parent Folder:** If a parent folder is deleted while the user is offline, any queued operations targeting that folder should be handled appropriately.

12 **Server Modifications:** The server might delete, rename, or modify a file that the user has also modified while offline. These conflicts need to be resolved when the user reconnects.

13. **Queue Operations After Delete:** The user might queue additional operations on a file or folder after it has been deleted. These operations must be managed correctly.

14. **Undo Delete Operations:** After deleting a file, the user might want to undo that operation. The system should support this.

**Comment by alperozturk96** [comment]
### Key Implementation Details:

- **OfflineOperationEntity Data Class:**
  - This class is used for managing offline operations in the database.
  - **Attributes:**
    - `id`: Unique identifier for the operation (nullable).
    - `parentOCFileId`: ID of the parent directory (nullable).
    - `parentPath`: Full path of the parent directory (nullable).
    - `type`: Type of offline operation (uses the `OfflineOperationType` enum).
    - `path`: Path where the operation will be executed.
    - `filename`: Name of the folder or file involved in the operation.
    - `createdAt`: Timestamp of when the operation was created.

- **OfflineOperationType Enum:**
  - Currently, it only has one value: `CreateFolder`.
  - As more offline operations are implemented, this enum will help distinguish between different types, determining the appropriate execution logic.

- **Handling `parentPath`:**
  - `parentPath` is critical as it represents the full path of the parent directory.
  - **Execution Constraint:** 
    - If an operation in the queue has a `null` `parentPath`, it cannot be executed because a folder cannot be created in a non-existent directory. The parent directory must exist before any sub-directory operations can be performed.
  - **Post-Execution Update:**
    - After successfully executing an offline operation, any matching top-level directories must be updated before continuing with other operations in the queue.

### **OfflineOperationsWorker Class:**
- **Purpose:**
  - This class is responsible for executing background jobs related to pending offline operations.
  
- **Triggers:**
  1. **Manual Trigger Depends On Internet Connectivity Status:** 
     - When the device reconnects to the internet and the server is reachable, the app triggers the worker to execute pending operations.
  2. **Periodic Trigger:** 
     - The worker is also registered to trigger automatically every 5 minutes to ensure that operations are retried periodically without relying solely on internet connection toggling.
  
- **Execution Logic:**
  - The worker checks for internet connectivity, server availability, and the presence of pending operations in the database. If all conditions are met, the worker begins processing the queue.

### **UI Considerations for Offline Operations:**
- **Supported Actions:**
  - **Rename:** Users can rename offline operation filenames.
  - **Delete:** Users can delete offline operations.

- **Unsupported Actions:**
  - **Move or Copy:** 
  - **Set as Favorite:**
  - **Encrypt/Decrypt:**
  - **Download:**

- **Operation Updates:**
  - If a user deletes or renames an offline operation, subsequent operations in the queue that depend on it must be updated accordingly.
  - **Examples:**
    - If the root directory for an operation is deleted, following operations should not be executed.
    - If the root directory’s name is changed, subsequent operations must be updated to reflect the new name to ensure successful execution.

### **Handling Duplicate Folder Creation:**
- **Conflict Resolution:**
  - If both the server and the user create the same folder while offline, the app provides options to resolve conflicts by choosing between the local, remote, or both versions of the folder.
  - **Naming Strategy:**
    - The conflict is resolved by appending the current date to the folder’s name for clear differentiation.
